version: "3.8"

services:
  # ================== Backend-серверы ==================
  backend1:
    build: ./app
    environment:
      - PORT=3000
      - SERVER_ID=backend-1
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MONGO_URI=mongodb://mongo:27017/usersdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - app-network

  backend2:
    build: ./app
    environment:
      - PORT=3000
      - SERVER_ID=backend-2
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MONGO_URI=mongodb://mongo:27017/usersdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - app-network

  # ================== Nginx Балансировщик ==================
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - backend2
    networks:
      - app-network

  # ================== Базы данных и Redis ==================
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:7
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    networks:
      - app-network

volumes:
  pgdata:
  mongodata:

networks:
  app-network:
    driver: bridge